name: heavenly_homes
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  google_sign_in: ^6.1.5
  provider: ^6.1.4
  go_router: ^14.8.1
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  cloud_firestore: ^5.6.6
  uuid: ^4.5.1
  google_fonts: ^6.1.0
  image_picker: ^0.8.6
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For more information on the generic Dart part of this file, see:
# https://dart.dev/tools/pub/pubspec 

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/chat_images/
    - assets/decoration-items/living-area/p1/
    - assets/decoration-items/living-area/p4/
    - assets/decoration-items/bed-room/p2/
    - assets/decoration-items/categories/
    - assets/interior-designs/damitha/luxury/office/
    - assets/interior-designs/damitha/modern/home1/
    - assets/interior-designs/amandi/modern/home1/
    - assets/logos/Splash screen main photo.png
    - assets/logos/app-logo.png
    - assets/logos/3D photo.png
    - assets/homescreen/Group 71.png
    - assets/homescreen/Group 72.png
    - assets/homescreen/Group 73.png
    - assets/homescreen/Main card1.png
    - assets/homescreen/Main card2.png
    - assets/homescreen/cart_icon.png
    - assets/images/

  fonts:
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: PoorStory
      fonts:
        - asset: assets/fonts/PoorStory-Regular.ttf